Update for CLAP 1.1.0
glowcoil/clap-sys pull request #19
Opened 2022-07-21 12:25 UTC by robbert-vdh

Based on https://github.com/free-audio/clap/compare/1.0.3...1.1.0.

- State context is a new draft extension.
- The voice info extension has been moved out of drafts.

2022-07-21 12:52 UTC, robbert-vdh commented
CLAP 1.1.1 is just a version bump on the Rust side.

2022-08-03 02:19 UTC, glowcoil requested changes

2022-08-03 02:19 UTC, glowcoil commented on src/ext/draft/mod.rs
> -pub mod voice_info;
Mind deleting the old `draft/voice_info.rs`?

2022-08-13 22:53 UTC, glowcoil commented on src/ext/draft/mod.rs
> -pub mod voice_info;
Will do this in a followup change.

2022-08-13 22:54 UTC, merged