Update for CLAP 1.1.8
glowcoil/clap-sys pull request #26
Opened 2023-03-13 14:40 UTC by robbert-vdh

Based on https://github.com/free-audio/clap/compare/1.1.7...1.1.8. Includes #25.

2023-10-18 00:06 UTC, glowcoil requested changes
Apologies for taking so long to review this.

2023-10-18 00:06 UTC, micahrj commented on src/ext/draft/configurable_audio_ports.rs
> +    pub port_details: *const c_char,
Should be `*const c_void`: https://github.com/free-audio/clap/blob/41964fa3f44fdbf6feb20df528a9cdf2cc3b05ba/include/clap/ext/draft/configurable-audio-ports.h#L34

2023-10-18 00:06 UTC, glowcoil commented on src/ext/draft/extensible_audio_ports.rs
> +            channel_count: u32,
Should be `index: u32`: https://github.com/free-audio/clap/blob/41964fa3f44fdbf6feb20df528a9cdf2cc3b05ba/include/clap/ext/draft/extensible-audio-ports.h#L28

2023-11-05 14:18 UTC, robbert-vdh commented on src/ext/draft/configurable_audio_ports.rs
> +    pub port_details: *const c_char,
Good catch, thanks! Fixed this and the other one.

2023-11-05 14:37 UTC, glowcoil approved these changes

2023-11-05 14:39 UTC, merged